[book]
title = "Roadster"
authors = ["Spencer Ferris"]
src = "src"
language = "en"
text-direction = "ltr"

[rust]
edition = "2024"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/roadster-rs/roadster"
edit-url-template = "https://github.com/roadster-rs/roadster/edit/main/book/{path}"
